/*
skiq_init()
skiq_write_rx_sample_rate_and_bandwidth()
skiq_write_tx_sample_rate_and_bandwidth()
skiq_write_rx_LO_freq()
skiq_write_tx_LO_freq()
skiq_write_tx/rx_LO_freq()
skiq_write_rx_LO_freq()
skiq_start_tx/rx_streaming()
skiq_start_tx/rx_streaming()
skiq_receive()
skiq_transmit()
*/